apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'fe-maintenance'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: 'chart'
    repoURL: 'https://github.com/gunawan-d/argocd-trial.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  project: 'default'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true