name: Build and Deployment Staging Branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout Branch
    - uses: actions/checkout@v3

    # Setting up Docker Builder
    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v2
    
    #Login Github Container Registry
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Push to Github Container Registry
    - name: Push to Github Container Registry
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          gunawand/{{ github.repository }}:${{ github.sha }}
          gunawand/{{ github.repository }}:latest
