name: Build and Deployment Staging Branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Branch
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fe-maintenance:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/fe-maintenance:latest

      # Update Helm Chart values.yaml with the new image tag
      - name: Update Helm Chart
        run: |
          chart_dir="chart"
          new_image_tag=${{ secrets.DOCKERHUB_USERNAME }}/fe-maintenance:${{ github.sha }}
          
          cd $chart_dir
          sed -i "s|__IMAGE__|$new_image_tag|g" values.yaml
          cat values.yaml
          
          git config --global user.name 'gunawan-d'
          git config --global user.email 'gunawandwi255@gmail.com'
          git add values.yaml
          git commit -m "Update image tag in Helm Chart"
          git push
