name: Build and Deployment Staging Branch

on:
  push:
    branches: [tag-name]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: argocd

    steps:
      # Checkout Branch
      - name: Checkout
        uses: actions/checkout@v4

      #Login Github Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: edufund-repository
          password: ${{ secrets.CR_PAT }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: branch name & tag name
        run: |
          IMAGE_NAME=mydockerimage
          BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///') 
          SHORT_SHA=${GITHUB_SHA::7}
          echo "TAG_NAME=${BRANCH_NAME}-${SHORT_SHA}" >> $GITHUB_ENV
      
      - name: check tagname 
        run: |
          echo "$TAG_NAME"

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/edufund-tech/front-maintenance:${{ TAG_NAME }}
            ghcr.io/edufund-tech/front-maintenance:stg

      - name: Update Image Tag Values
        run: |
          chart_dir="chart"
          new_image_tag=${{ github.sha }}
          echo "chart_dir: $chart_dir"
          echo "new_image_tag: $new_image_tag"
          cd "$chart_dir"
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "./values.yaml"
          cat values.yaml
      
      - name: Commit and Push Changes
        run: |
          new_image_tag=${{ github.sha }}
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@edufund.co.id"
          git add .
          git commit -m "Update image tag in Helm Chart - $new_image_tag"
          git push
