name: Build and Deployment Staging Branch

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Branch
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push Docker image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gunawand/fe-maintenance:${{ github.sha }}
            gunawand/fe-maintenance:latest
      
      - name: Update Image Tag Values
        run: |
          chart_dir="chart"
          new_image_tag=${{ github.sha }}
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values.yaml"

  